version: '3'

services:
  ros2_control:
    build: .
    container_name: franka_ros2
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspaces
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
      - ./limits.conf:/etc/security/limits.conf
      - ~/.gitconfig:/etc/gitconfig:ro
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      PATH: /opt/openrobots/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PKG_CONFIG_PATH: /opt/openrobots/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
      LD_LIBRARY_PATH: /opt/openrobots/lib:/usr/local/lib:/usr/lib
      PYTHONPATH: /opt/openrobots/lib/python3.10/site-packages:/usr/local/lib/python3.10/site-packages
      CMAKE_PREFIX_PATH: /opt/openrobots:/usr/local
    user: $UID:$UID
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
